### ISSUE TITLE
[feat] call to action bunner

### ISSUE THREAD

**Issue by mirus-ua** [mirus-ua/hugo-theme-re-terminal#1]
Add a banner at the top of the site with any call to action with an attached link

```toml
# you can set a banner on the top of the page with a call to action
 # defaults: dismissible = false; URL is optional
[params.banner]
dismissible = false
text = "Check it out on GitHub"
url = "https://github.com/mirus-ua/hugo-theme-re-terminal"
```
