### ISSUE TITLE
Media queries not working properly

### ISSUE THREAD

**Issue by AranjuezY** [mirus-ua/hugo-theme-re-terminal#28]
The css variables associated to media queries are defined as --phone and --tablet. In fact, CSS media queries cannot get these two variables. 
I replaced these variables with scss variables:
```scss
:root {
  /* COLOR VARIABLES */
  ...
}

/* MEDIA QUERIES */
$phone: 684px;
$tablet: 900px;
```
And replaced all related styles like this:
```scss
  @media (max-width: $phone) {
    font-size: 1rem;
  }
```
Then the styles work fine on my mobile phone.
