### ISSUE TITLE
Reading time not working

### ISSUE THREAD

**Issue by sid314** [mirus-ua/hugo-theme-re-terminal#37]
i have set readingTime = true still it dosent work. Do I need to add something else?

**Comment by mirus-ua** [comment]
Can you confirm that you config looks similar to this? 
```toml
[params]
  readingTime = true
```
